#!/bin/bash
set -e

# Define env vars with suffix __SECRET_FILE then
# This var env will be loaded by reading file associated, example:
#
# export FOO__SECRET_FILE='/tmp/douda'
# echo 'chuck' > /tmp/douda
# docker-secret-entrypoint php -r 'var_dump(getenv("FOO"));'
# will output => chuck

file_env() {
	local var="$1"
	local fileVar="${var}__SECRET_FILE"
	local def="${2:-}"
	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
		exit 1
	fi
	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi
	export "$var"="$val"
	unset "$fileVar"
}

while IFS='=' read -r name value ; do
    if [[ $name == *__SECRET_FILE ]]
    then
        secret=${name%__SECRET_FILE*}
        file_env $secret;
    fi
done < <(env)

exec "$@"
